# Generated by Django 4.1.2 on 2022-12-01 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rename_apellido_usuario_clave_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bandejatrabajo',
            fields=[
                ('idot', models.BigIntegerField(primary_key=True, serialize=False)),
                ('idreserva', models.BigIntegerField()),
                ('rutempleado', models.BigIntegerField()),
                ('descripcionot', models.CharField(max_length=50)),
                ('totalot', models.BigIntegerField()),
                ('fechaot', models.DateField()),
                ('estadoot', models.BigIntegerField()),
                ('categoriaot', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('rutcliente', models.BigIntegerField(primary_key=True, serialize=False)),
                ('dvcliente', models.CharField(max_length=1)),
                ('nombre', models.CharField(max_length=50)),
                ('appaterno', models.CharField(max_length=50)),
                ('apmaterno', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('rutempleado', models.BigIntegerField(primary_key=True, serialize=False)),
                ('dvempleado', models.CharField(max_length=1)),
                ('nombre', models.CharField(max_length=50)),
                ('appaterno', models.CharField(max_length=50)),
                ('apmaterno', models.CharField(max_length=50)),
                ('rol', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Facturacion',
            fields=[
                ('nrodocumento', models.BigIntegerField(primary_key=True, serialize=False)),
                ('tipodocumento', models.CharField(max_length=50)),
                ('idot', models.BigIntegerField()),
                ('ot_idot', models.BigIntegerField()),
                ('ot_idreserva', models.BigIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Ot',
            fields=[
                ('idot', models.BigIntegerField(primary_key=True, serialize=False)),
                ('idreserva', models.BigIntegerField()),
                ('rutempleado', models.BigIntegerField()),
                ('descripcionot', models.CharField(max_length=50)),
                ('totalot', models.BigIntegerField()),
                ('fechaot', models.DateField(blank=True, null=True)),
                ('reserva_idreserva', models.BigIntegerField()),
                ('facturacion_nrodocumento', models.BigIntegerField()),
                ('facturacion_idot', models.BigIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Productos',
            fields=[
                ('idproducto', models.BigIntegerField(primary_key=True, serialize=False)),
                ('nombreproducto', models.CharField(max_length=50)),
                ('cantidad', models.BigIntegerField()),
                ('tipoproducto', models.CharField(max_length=50)),
                ('marcaproducto', models.CharField(max_length=50)),
                ('idvehiculo', models.BigIntegerField()),
                ('valorproducto', models.BigIntegerField()),
                ('rutproveedor', models.BigIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('rutproveedor', models.BigIntegerField(primary_key=True, serialize=False)),
                ('dvproveedor', models.CharField(max_length=1)),
                ('nombreproveedor', models.CharField(max_length=50)),
                ('direccionproveedor', models.CharField(max_length=50)),
                ('telefonocontacto', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('idreserva', models.BigIntegerField(primary_key=True, serialize=False)),
                ('rutcliente', models.BigIntegerField()),
                ('idservicio', models.BigIntegerField()),
                ('fechareserva', models.DateField()),
                ('horareserva', models.DateField()),
                ('canal', models.CharField(max_length=50)),
                ('patente', models.CharField(max_length=50)),
                ('idvehiculo', models.BigIntegerField()),
                ('ot_idot', models.BigIntegerField()),
                ('ot_idreserva', models.BigIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('idservicio', models.BigIntegerField(primary_key=True, serialize=False)),
                ('tiposervicio', models.CharField(max_length=50)),
                ('descservicio', models.CharField(max_length=50)),
                ('valorservicio', models.BigIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Vehiculos',
            fields=[
                ('idvehiculo', models.BigIntegerField(primary_key=True, serialize=False)),
                ('marca', models.CharField(max_length=50)),
                ('modelo', models.CharField(max_length=50)),
                ('anio', models.BigIntegerField()),
                ('tipovehiculo', models.CharField(max_length=50)),
                ('cilindrada', models.BigIntegerField()),
                ('vin', models.CharField(max_length=50)),
                ('reserva_idreserva', models.BigIntegerField()),
            ],
        ),
    ]
