# Generated by Django 4.1.2 on 2022-12-01 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_bandejatrabajo_cliente_empleado_facturacion_ot_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ot',
            name='reserva_idreserva',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='fechareserva',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='horareserva',
            field=models.CharField(max_length=50),
        ),
    ]
