# Generated by Django 4.1.2 on 2022-12-01 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_ot_reserva_idreserva_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bandejatrabajo',
            name='fechaot',
            field=models.CharField(max_length=50),
        ),
    ]
