# Generated by Django 4.0.4 on 2023-05-25 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_delete_cliente_delete_empleado_delete_facturacion_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bandeja',
            fields=[
                ('ot', models.BigIntegerField(primary_key=True, serialize=False)),
                ('cliente', models.CharField(max_length=50)),
                ('ingreso', models.CharField(max_length=50)),
                ('equipo', models.CharField(max_length=50)),
                ('termino', models.CharField(max_length=50)),
                ('tarea', models.CharField(max_length=50)),
                ('rutempleado', models.BigIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('rut', models.BigIntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('telefono', models.BigIntegerField()),
                ('email', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=50)),
                ('clave', models.CharField(max_length=50)),
                ('rol', models.CharField(max_length=50)),
            ],
        ),
    ]
