# Generated by Django 4.0.4 on 2023-05-25 02:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_bandeja_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='clave',
        ),
    ]
